// Import the raw glue code generated by wasm-pack (esbuild will inline its contents during bundling)
import {
  compress_lzip,
  compress_lzma,
  compress_xz,
  decompress_dynamic,
  decompress_to_buffer,
  default as init,
  initSync,
} from "../pkg/lzma_wasm.js";
// Import the Base64 string dynamically generated by the build script
import { WASM_BASE64 } from "./wasm-b64.js";

let isReady = false;

const MEM_LIMIT = 1024 * 1024 * 256; // Default memory limit of 256MB to prevent OOM errors caused by malicious files

function getWasmBytes(): Uint8Array{
  // Cross-environment Base64 decoding logic
  if (typeof Buffer !== "undefined") {
    // Node.js environment: High-speed decoding
    return Buffer.from(WASM_BASE64, "base64");
  } else {
    // Browser / Deno environments: Native `atob` decoding
    const str = atob(WASM_BASE64);
    const wasmBytes = new Uint8Array(str.length);
    for (let i = 0; i < str.length; i++) {
      wasmBytes[i] = str.charCodeAt(i);
    }
    return wasmBytes;
  }
}

/**
 * Initializes the WebAssembly environment.
 * * **CRITICAL:** This function must be awaited and resolved before calling any other
 * compression or decompression APIs. It safely handles cross-platform Wasm instantiation
 * for both Node.js and Browser environments.
 * * It is safe to call this multiple times; subsequent calls will immediately return
 * if the environment is already initialized.
 * 
 * @returns {Promise<void>} A promise that resolves when the Wasm module is ready to use.
 * @example
 * import { initWasm, compress } from 'lzma-wasm-universal';
 * await initWasm();
 * const compressed = compress(data);
 */
export async function initWasm(): Promise<void> {
  if (isReady) return;

  let wasmBytes: Uint8Array = getWasmBytes();

  // Feed the byte stream to the `init` function provided by wasm-bindgen
  await init({ module_or_path: wasmBytes });
  isReady = true;
}


/**
 * Initializes the WebAssembly environment.
 * * **CRITICAL:** This function must be awaited and resolved before calling any other
 * compression or decompression APIs. It safely handles cross-platform Wasm instantiation
 * for both Node.js and Browser environments.
 * * It is safe to call this multiple times; subsequent calls will immediately return
 * if the environment is already initialized.
 * 
 * @returns {void} Returns when it is ready to use.
 * @example
 * import { initWasmSync, compress } from 'lzma-wasm-universal';
 * initWasmSync();
 * const compressed = compress(data);
 */
export function initWasmSync(): void {
  if (isReady) return;

  let wasmBytes: Uint8Array = getWasmBytes();
  // Feed the byte stream to the `init` function provided by wasm-bindgen
  initSync({ module: wasmBytes });
  isReady = true;
}

/**
 * Configuration options for the decompression process.
 */
export interface DecompressOptions {
  /** * The exact expected size of the uncompressed data in bytes.
   * * **⚡ Performance Tip:** Providing this value enables the "Zero-Allocation" 
   * high-performance mode. The library will pre-allocate the exact required memory 
   * in JavaScript and instruct WebAssembly to write directly into it, avoiding 
   * internal Rust vector resizing and reducing cross-boundary memory copying.
   */
  expectedSize?: number;
  /** * The maximum amount of memory (in bytes) the Wasm decompressor is allowed to allocate.
   * * This acts as a crucial safeguard against malicious, highly-compressed files 
   * (e.g., Zip Bombs) that could cause Out-Of-Memory (OOM) crashes.
   * 
   * @default 268435456 (256 MB)
   */
  memLimit?: number;
}

/**
 * Decompresses LZMA, XZ, or LZIP binary data.
 * * The function automatically detects the compression format based on the magic headers
 * of the provided compressed data.
 * 
 * @param {Uint8Array} compressed - The compressed binary data.
 * @param {DecompressOptions} [options] - Optional configuration for decompression memory strategies.
 * @returns {Uint8Array} A new Uint8Array containing the uncompressed data.
 * @throws {Error} If the Wasm module is not initialized, the format is invalid, or memory limits are exceeded.
 */
export function decompress(
  compressed: Uint8Array,
  options?: DecompressOptions,
): Uint8Array {
  if (!isReady) throw new Error("Please call `initWasm()` and wait for initialization to complete first");

  if (options?.expectedSize) {
    // Follow the high-performance path using pre-allocated memory
    const outBuffer = new Uint8Array(options.expectedSize);
    const bytesWritten = decompress_to_buffer(
      compressed,
      outBuffer,
      options.memLimit ?? MEM_LIMIT,
    );
    // If the actual file size is smaller than allocated, truncate the unused portion
    return outBuffer.subarray(0, bytesWritten);
  } else {
    // Follow the Rust dynamic memory expansion path
    const memLimit = options?.memLimit ?? MEM_LIMIT;
    return decompress_dynamic(compressed, memLimit);
  }
}

/**
 * Expert-level Decompression API (Zero-Allocation).
 * * Decompresses data directly into a pre-allocated JavaScript `Uint8Array`.
 * 
 * This bypasses internal dynamic reallocation and minimizes GC (Garbage Collection) pressure, 
 * making it ideal for high-frequency or extreme-performance scenarios (e.g., game assets, video streaming).
 * 
 * @param {Uint8Array} compressed - The compressed binary data.
 * @param {Uint8Array} outBuffer - The pre-allocated destination buffer. It must be large enough to hold the uncompressed data.
 * @param {number} [memLimit] - Optional memory limit in bytes to prevent OOM. If not provided, it defaults to the size of `outBuffer`.
 * @returns {number} The actual number of bytes written to the `outBuffer`.
 * @throws {Error} If the uncompressed data exceeds the size of `outBuffer` or if decompression fails.
 */
export function decompressToBuffer(
  compressed: Uint8Array,
  outBuffer: Uint8Array,
  memLimit?: number,
): number {
  if (!isReady) throw new Error("Please call `initWasm()` and wait for initialization to complete first");
  return decompress_to_buffer(compressed, outBuffer, memLimit ?? MEM_LIMIT);
}

/**
 * Configuration options for the compression process.
 */
export interface CompressOptions {
  /** The target compression format.
   * - `'xz'`: (Recommended) Modern, highly efficient container format with integrity checks (CRC).
   * - `'lzip'`: Designed for long-term archiving and data recovery reliability.
   * - `'lzma'`: Legacy format (LZMA Alone), widely supported but lacks robust headers.
   * * @default "xz"
   */
  format?: "lzma" | "xz" | "lzip";
  /** The compression preset level, ranging from `0` to `9`.
   * - `0-2`: Fastest compression speed, lowest memory usage, lower compression ratio.
   * - `3-6`: Balanced performance. `6` is the standard default for most command-line tools.
   * - `7-9`: Maximum compression ratio, extremely slow, highest memory usage.
   * 
   * @default 6
   */
  level?: number;
}

/**
 * Compresses binary data into the specified LZMA-family format.
 * @param {Uint8Array} data - The raw, uncompressed binary data to be compressed.
 * @param {CompressOptions} [options] - Configuration for the output format and compression level.
 * @returns {Uint8Array} A new Uint8Array containing the compressed binary data.
 * @throws {Error} If the Wasm module is not initialized or if the compression process fails.
 */
export function compress(
  data: Uint8Array,
  options?: CompressOptions,
): Uint8Array {
  if (!isReady) throw new Error("Please call `initWasm()` and wait for initialization to complete first");
  // Default behavior: Use xz format with level 6 (consistent with Linux default behavior)
  const format = options?.format ?? "xz";
  const level = options?.level ?? 6;

  // Safety check: Prevent users from entering out-of-bounds values
  const safeLevel = Math.max(0, Math.min(9, Math.floor(level)));

  try {
    switch (format) {
      case "xz":
        return compress_xz(data, safeLevel);
      case "lzip":
        return compress_lzip(data, safeLevel);
      case "lzma":
      default:
        return compress_lzma(data, safeLevel);
    }
  } catch (err) {
    throw new Error(`[LZMA-Wasm] Compression failed (${format}): ${err}`);
  }
}
